
// let data=[
//     {
//         name:"vishal"
//         ,
//         id:"101"
//         ,
//         city:"hajipur"
//     },
//      {
//         name:"vishal"
//         ,
//         id:"101"
//         ,
//         city:"hajipur"
//     },
//      {
//         name:"vishal"
//         ,
//         id:"101"
//         ,
//         city:"hajipur"
//     },
//      {
//         name:"vishal"
//         ,
//         id:"101"
//         ,
//         city:"hajipur"
//     },
//      {
//         name:"vishal"
//         ,
//         id:"101"
//         ,
//         city:"hajipur"
//     }
// ]